# Generated by Django 5.2.4 on 2026-04-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(blank=True, help_text='Upload an MP4 video file', null=True, upload_to='reels/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Or paste an external video URL (MP4 direct link)', null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image shown before hover', null=True, upload_to='reels/thumbnails/')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reel',
                'verbose_name_plural': 'Reels',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
