# Generated by Django 5.2.4 on 2026-04-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='video_url',
        ),
    ]
