# Generated by Django 4.2.1 on 2023-08-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seo_optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(default=None, max_length=255, null=True, verbose_name='Page Name')),
                ('metatitle', models.CharField(default=None, max_length=60, null=True, verbose_name='Page Meta Title')),
                ('metadescription', models.TextField(default=None, max_length=160, null=True, verbose_name='Page Meta Des')),
                ('pageslug', models.CharField(default=None, max_length=160, null=True, verbose_name='Page Url')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_status', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
