# Generated by Django 4.1 on 2024-05-25 07:44

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Seo_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo_optimization',
            name='post_status',
        ),
        migrations.AddField(
            model_name='seo_optimization',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seo_optimization',
            name='order',
            field=models.IntegerField(default=5, null=True, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='seo_optimization',
            name='pagecontent',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='No News', null=True, verbose_name='Long Discretion'),
        ),
        migrations.AddField(
            model_name='seo_optimization',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='seo_optimization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seo_optimization',
            name='metadescription',
            field=models.TextField(default=None, max_length=165, null=True, verbose_name='Page Meta Des'),
        ),
        migrations.AlterField(
            model_name='seo_optimization',
            name='metatitle',
            field=models.CharField(default=None, max_length=65, null=True, verbose_name='Page Meta Title'),
        ),
        migrations.AlterField(
            model_name='seo_optimization',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
