# Generated by Django 4.2.7 on 2025-04-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seo_management', '0002_remove_seo_optimization_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo_optimization',
            name='metadescription',
            field=models.TextField(default=None, max_length=175, null=True, verbose_name='Page Meta Des'),
        ),
        migrations.AlterField(
            model_name='seo_optimization',
            name='metatitle',
            field=models.CharField(default=None, max_length=75, null=True, verbose_name='Page Meta Title'),
        ),
    ]
