# Generated by Django 4.2.1 on 2023-06-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog',
            name='tbl_image',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='blog/'),
        ),
    ]
