# Generated by Django 4.2.1 on 2023-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_tbl_blog_tbl_blog_des_alter_tbl_blog_tbl_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog',
            name='tbl_blog_slug',
            field=models.SlugField(auto_created=models.CharField(max_length=255), default=None, null=True),
        ),
    ]
