# Generated by Django 4.2.1 on 2023-06-29 13:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_tbl_blog_tbl_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog',
            name='tbl_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='tbl_blog_cat', unique=True),
        ),
    ]
