# Generated by Django 4.2.1 on 2023-06-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_tbl_blog_tbl_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_blog',
            old_name='tbl_blog_date',
            new_name='blog_date',
        ),
        migrations.RenameField(
            model_name='tbl_blog',
            old_name='tbl_blog_des',
            new_name='blog_des',
        ),
        migrations.RenameField(
            model_name='tbl_blog',
            old_name='tbl_image',
            new_name='blog_image',
        ),
        migrations.RenameField(
            model_name='tbl_blog',
            old_name='tbl_blog_status',
            new_name='blog_status',
        ),
        migrations.RenameField(
            model_name='tbl_blog',
            old_name='tbl_blog_cat',
            new_name='blog_title',
        ),
        migrations.RenameField(
            model_name='tbl_blog',
            old_name='tbl_slug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='tbl_blog',
            name='tbl_blog_blog',
        ),
        migrations.RemoveField(
            model_name='tbl_blog',
            name='tbl_blog_icon',
        ),
        migrations.RemoveField(
            model_name='tbl_blog',
            name='tbl_blog_slug',
        ),
    ]
