# Generated by Django 4.2.1 on 2023-06-30 08:11

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_tbl_blog_date_tbl_blog_blog_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_image', models.FileField(default=None, max_length=255, null=True, upload_to='blog/')),
                ('blog_des', tinymce.models.HTMLField(default=None, null=True)),
                ('blog_status', models.IntegerField(default=0, null=True)),
                ('blog_date', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_title', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_blog',
        ),
    ]
