# Generated by Django 4.2.1 on 2023-06-30 09:32

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_blog_delete_tbl_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('cat_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='cat_name', unique=True)),
                ('cat_status', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_meta_des',
            field=models.CharField(default=None, max_length=160, null=True, verbose_name='Meta Des'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default=None, max_length=40, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_cat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.blog_category', verbose_name='Select Cetegory'),
        ),
    ]
