# Generated by Django 4.2.1 on 2023-07-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_blog_category_blog_blog_meta_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_category',
            name='parent_cat',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.blog_category', verbose_name='Select Parent'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default=None, max_length=65, null=True, verbose_name='Title'),
        ),
    ]
