# Generated by Django 4.2.1 on 2023-07-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_blog_category_parent_cat_alter_blog_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_category',
            name='parent_cat',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='service.blog_category', verbose_name='Select Parent'),
        ),
    ]
