# Generated by Django 4.2.1 on 2023-07-17 13:16

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_blog_category_parent_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_category',
            name='parent_cat',
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('subcat_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='cat_name', unique=True)),
                ('subcat_status', models.IntegerField(default=0, null=True)),
                ('parent_cat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.blog_category', verbose_name='Select parent Cetegory')),
            ],
        ),
    ]
