# Generated by Django 4.2.1 on 2023-07-18 08:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_blog_category_parent_cat_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='subcat_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='parent_cat', unique=True),
        ),
    ]
