# Generated by Django 4.2.1 on 2023-07-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_sub_category_subcat_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_meta_des',
            new_name='blog_short_des',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_make_banner',
            field=models.CharField(default=None, max_length=2, null=True, verbose_name='Make Banner'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_tag',
            field=models.TextField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
