# Generated by Django 4.2.1 on 2023-07-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_blog_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cropping',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
