# Generated by Django 4.2.1 on 2023-07-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_remove_blog_cropping_blog_is_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_make_banner',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_banner',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Make Banner'),
        ),
    ]
