# Generated by Django 4.2.1 on 2023-07-24 06:47

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_blog_image_crop_alter_blog_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_cat_name', models.CharField(default=None, max_length=255, null=True, unique=True, verbose_name='Ad Type')),
                ('ads_cat_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='cat_name', unique=True)),
                ('ads_cat_status', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_crop',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='blog/'),
        ),
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_url', models.CharField(default=None, max_length=255, null=True, verbose_name='Link URL')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('ad_image', models.FileField(upload_to='ads/')),
                ('ad_counter', models.IntegerField(default=None, null=True, verbose_name='Counter')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_status', models.IntegerField(default=0, null=True)),
                ('ads_cat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ads_category', verbose_name='Select Ad Type')),
            ],
        ),
    ]
