# Generated by Django 4.2.1 on 2023-07-24 08:31

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_rename_ads_ad_rename_ads_category_ad_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='seo_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(default=None, max_length=255, null=True, verbose_name='Page Name')),
                ('metatitle', models.CharField(default=None, max_length=60, null=True, verbose_name='Page Meta Title')),
                ('metadescription', models.CharField(default=None, max_length=160, null=True, verbose_name='Page Meta Des')),
                ('pageslug', models.CharField(default=None, max_length=160, null=True, verbose_name='Page Meta Des')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_status', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ad_category',
            name='ads_cat_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='ads_cat_name', unique=True),
        ),
    ]
