# Generated by Django 4.2.1 on 2023-07-27 08:28

import autoslug.fields
from django.db import migrations, models
import image_cropping.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_seo_management_alter_ad_category_ads_cat_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='videopost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videotype', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football')], default='active', max_length=255, verbose_name='Video Type')),
                ('video_title', models.CharField(default=None, max_length=60, null=True, verbose_name='Title (Lenth 60 Char)')),
                ('video_short_des', models.CharField(default=None, max_length=160, null=True, verbose_name='Meta/Short Des')),
                ('video_des', tinymce.models.HTMLField(default=None, null=True)),
                ('video_url', models.CharField(default=True, max_length=255, null=True, verbose_name='Youtube Video URL')),
                ('thumnail', image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='vidimage/')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='video_title', unique=True)),
                ('video_tag', models.CharField(default=0, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('video_date', models.DateTimeField(auto_now=True)),
                ('video_status', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='seo_management',
            name='metadescription',
            field=models.TextField(default=None, max_length=160, null=True, verbose_name='Page Meta Des'),
        ),
        migrations.AlterField(
            model_name='seo_management',
            name='pageslug',
            field=models.CharField(default=None, max_length=160, null=True, verbose_name='Page Url'),
        ),
    ]
