# Generated by Django 4.1 on 2023-08-07 12:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_alter_blog_blog_des_alter_videopost_videotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_des',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, null=True),
        ),
    ]
