# Generated by Django 4.2.1 on 2023-08-08 10:41

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_post_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_name', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('subcat_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='cat_name', unique=True)),
                ('subcat_status', models.IntegerField(default=0, null=True)),
                ('sub_cat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='Select Cetegory')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post_cat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.sub_category', verbose_name='Select Cetegory'),
        ),
    ]
