# Generated by Django 4.2.1 on 2023-08-08 11:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_sub_category_alter_post_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='subcat_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='subcat_name', unique=True),
        ),
    ]
