# Generated by Django 4.1 on 2023-12-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_alter_sub_category_subcat_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default=None, max_length=65, null=True, verbose_name='Name')),
                ('education', models.CharField(default=None, max_length=100, null=True, verbose_name='Higher Education')),
                ('experience', models.CharField(default=None, max_length=160, null=True, verbose_name='Work Experience')),
                ('expsalary', models.CharField(default=None, max_length=160, null=True, verbose_name='Expected Salary')),
                ('covernote', models.TextField(default='na', null=True, verbose_name='Cover Note')),
                ('resume', models.FileField(default=None, max_length=255, null=True, upload_to='cv/')),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('NotSelected', 'Not Selected')], default='NotSelected', max_length=20)),
                ('remark', models.TextField(default='na', null=True, verbose_name='Remark')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='Select Category')),
            ],
        ),
    ]
