# Generated by Django 4.1 on 2023-12-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0004_alter_videonews_news_category'),
        ('service', '0028_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ads_cat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_cat',
        ),
        migrations.DeleteModel(
            name='seo_management',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='sub_cat',
        ),
        migrations.DeleteModel(
            name='videopost',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.category', verbose_name='Select Category'),
        ),
        migrations.DeleteModel(
            name='ad',
        ),
        migrations.DeleteModel(
            name='ad_category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
