# Generated by Django 4.1 on 2023-12-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0005_alter_newspost_is_active_alter_newspost_post_image_and_more'),
        ('service', '0029_remove_ad_ads_cat_remove_post_post_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True, verbose_name='Name')),
                ('mobnumber', models.CharField(default=None, max_length=100, null=True, verbose_name='Name')),
                ('email', models.CharField(default=None, max_length=160, null=True, verbose_name='email')),
                ('location', models.CharField(default=None, max_length=160, null=True, verbose_name='location')),
                ('nationality', models.CharField(default=None, max_length=160, null=True, verbose_name='nationality')),
                ('language', models.CharField(default=None, max_length=160, null=True, verbose_name='language')),
                ('address', models.TextField(default='na', null=True, verbose_name='address')),
                ('highestedu', models.CharField(default=None, max_length=100, null=True, verbose_name='Higher Education')),
                ('fos', models.CharField(default=None, max_length=100, null=True, verbose_name='FieldOfStudy')),
                ('occupation', models.CharField(default=None, max_length=160, null=True, verbose_name='occupation')),
                ('journalexp', models.CharField(default=None, max_length=160, null=True, verbose_name='journalexp')),
                ('lastwork', models.CharField(default=None, max_length=160, null=True, verbose_name='lastwork')),
                ('portfolio', models.CharField(default=None, max_length=160, null=True, verbose_name='Portfolio')),
                ('equipment', models.CharField(default=None, max_length=160, null=True, verbose_name='Equipment')),
                ('softwareskill', models.CharField(default=None, max_length=160, null=True, verbose_name='Softwareskill')),
                ('availability', models.CharField(default=None, max_length=160, null=True, verbose_name='Availability')),
                ('resume', models.FileField(default=None, max_length=255, null=True, upload_to='cv/')),
                ('whyjoin', models.TextField(default='na', null=True, verbose_name='Why Join')),
                ('anysegment', models.TextField(default='na', null=True, verbose_name='Anysegment')),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('NotSelected', 'Not Selected')], default='NotSelected', max_length=20)),
                ('remark', models.TextField(default='na', null=True, verbose_name='Remark')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Latest News')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.category', verbose_name='Select Category')),
            ],
        ),
    ]
