# Generated by Django 4.1 on 2024-01-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_subscribeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email')),
                ('Logo', models.FileField(default=None, max_length=255, null=True, upload_to='bplogo/')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
