# Generated by Django 4.1 on 2024-03-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0017_alter_videonews_order_and_more'),
        ('service', '0033_brandpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255, null=True, verbose_name='Person Name')),
                ('company_name', models.CharField(max_length=255, null=True, verbose_name='Company Name')),
                ('company_address', models.CharField(max_length=255, null=True, verbose_name='Company Address')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='phone')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='email')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='city')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='country')),
                ('diesgantion', models.CharField(max_length=255, null=True, verbose_name='diesgantion')),
                ('enquiry_type', models.CharField(max_length=255, null=True, verbose_name='enquiry_type')),
                ('executive_names', models.CharField(max_length=255, null=True, verbose_name='executive names')),
                ('walk_in', models.CharField(max_length=255, null=True, verbose_name='walk_in')),
                ('ip', models.CharField(max_length=255, verbose_name='User Ip')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('source_from', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.sub_category', verbose_name='Select Category')),
            ],
        ),
    ]
