# Generated by Django 4.1 on 2024-03-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_regform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='diesgantion',
            field=models.CharField(max_length=255, null=True, verbose_name='Designation'),
        ),
    ]
