# Generated by Django 4.1 on 2024-11-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_alter_regform_diesgantion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('age', models.CharField(blank=True, choices=[('young-children', 'Young Children (5–12y)'), ('teenagers', 'Teenagers (13–19y)'), ('young-adults', 'Young Adults (20–35y)'), ('adults', 'Adults (36–60y)'), ('senior-citizens', 'Senior Citizens (60+)')], max_length=20, null=True)),
                ('Cross_Sector', models.CharField(blank=True, choices=[('science-technology', 'Science and Technology'), ('entrepreneurship', 'Entrepreneurship'), ('environment', 'Environment and Sustainability'), ('social-media', 'Social Media and Content Creation'), ('health-wellness', 'Health and Wellness'), ('civic-engagement', 'Civic Engagement'), ('diversity-inclusion', 'Diversity and Inclusion'), ('spirituality', 'Spirituality and Philosophy')], max_length=20, null=True)),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='phone')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='email')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='country')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='city')),
                ('description', models.TextField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('proof', models.FileField(upload_to='proofs/')),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_payment', models.BooleanField(default=False)),
            ],
        ),
    ]
