# Generated by Django 4.2.7 on 2025-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0036_adsenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='vouenquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('interestedin', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='vouprofilepic/')),
                ('biography', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('done', 'Done'), ('pending', 'Pending')], default='Article Live', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
