# Generated by Django 5.2.3 on 2026-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0037_vouenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='company_address',
            field=models.CharField(max_length=1000, null=True, verbose_name='Company Address'),
        ),
    ]
