# Generated by Django 5.2.3 on 2026-03-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_alter_regform_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='company_address',
            field=models.TextField(null=True, verbose_name='Company Address'),
        ),
    ]
