# Generated by Django 5.2.4 on 2025-12-26 07:54

import django.db.models.deletion
import webstories.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebStoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Web Story Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Story title (max 70 chars for SEO)', max_length=70)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('poster_portrait', models.ImageField(help_text='Vertical image 720x1280px (Required for AMP)', upload_to='webstories/posters/', validators=[webstories.models.validate_image_size, webstories.models.validate_vertical_image])),
                ('publisher_name', models.CharField(default='Newsible', help_text='Publisher name for AMP stories (REQUIRED by Google AMP)', max_length=100)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description (150-160 characters)', max_length=160, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='webstories.webstorycategory')),
            ],
            options={
                'verbose_name_plural': 'AMP Web Stories',
                'ordering': ['order', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='WebStoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose image or video for this page', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Vertical image 720x1280px (Required if media type is Image)', null=True, upload_to='webstories/pages/', validators=[webstories.models.validate_image_size, webstories.models.validate_vertical_image])),
                ('video', models.FileField(blank=True, help_text='MP4 video file (vertical 720x1280 recommended, max 10MB)', null=True, upload_to='webstories/videos/')),
                ('video_poster', models.ImageField(blank=True, help_text='Thumbnail for video (720x1280px, shown while video loads)', null=True, upload_to='webstories/video_posters/', validators=[webstories.models.validate_image_size, webstories.models.validate_vertical_image])),
                ('heading', models.CharField(help_text='Short heading for this page', max_length=100)),
                ('text', models.TextField(help_text='Max 200 characters (Google recommendation)', max_length=200)),
                ('credit', models.CharField(blank=True, help_text="Photo/Video credit (e.g., 'Photo: Reuters' or 'Video: AFP')", max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=5, help_text='Duration in seconds before auto-advancing to next page (3-15 seconds recommended)')),
                ('layout', models.CharField(choices=[('vertical', 'Vertical (Text at bottom)'), ('thirds', 'Thirds (Text in middle)')], default='vertical', help_text='Text layout position', max_length=20)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='webstories.webstory')),
            ],
            options={
                'verbose_name': 'Story Page',
                'verbose_name_plural': 'Story Pages',
                'ordering': ['order'],
            },
        ),
    ]
