# Generated by Django 5.2.4 on 2026-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstorypage',
            name='heading',
            field=models.CharField(blank=True, help_text='Short heading for this page', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webstorypage',
            name='text',
            field=models.TextField(blank=True, help_text='Max 200 characters (Google recommendation)', max_length=200, null=True),
        ),
    ]
