# Generated by Django 5.2.4 on 2026-04-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstories', '0002_alter_webstorypage_heading_alter_webstorypage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstory',
            name='publisher_name',
            field=models.CharField(default='dxbnewsnetwork', help_text='Publisher name for AMP stories (REQUIRED by Google AMP)', max_length=100),
        ),
    ]
