# Generated by Django 5.2.4 on 2026-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstories', '0003_alter_webstory_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstory',
            name='publisher_name',
            field=models.CharField(default='Dxb News Network', help_text='Publisher name for AMP stories (REQUIRED by Google AMP)', max_length=100),
        ),
    ]
