# Generated by Django 5.1.4 on 2025-05-01 14:10

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='pageimage',
            field=image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to='cms/', verbose_name='Page Image (1280X220px)'),
        ),
    ]
