# Generated by Django 5.1.4 on 2025-05-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_cms_pageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_setting',
            name='items_background',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='items background in body', max_length=7, null=True, verbose_name='Items background'),
        ),
    ]
