# Generated by Django 4.1 on 2023-11-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Head_Lines',
            field=models.BooleanField(default=False, verbose_name='Head Lines'),
        ),
        migrations.AddField(
            model_name='post',
            name='articles',
            field=models.BooleanField(default=False, verbose_name='Articles'),
        ),
        migrations.AddField(
            model_name='post',
            name='trending',
            field=models.BooleanField(default=False, verbose_name='Trending'),
        ),
    ]
