# Generated by Django 4.1 on 2023-12-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0003_newspost_videonews_alter_category_cat_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videonews',
            name='News_Category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.sub_category', verbose_name='Select Category'),
        ),
    ]
