# Generated by Django 4.1 on 2023-12-13 18:07

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0004_alter_videonews_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Latest News'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_image',
            field=image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='blog/', verbose_name='News Image (900X468px)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_status',
            field=models.IntegerField(default=100, null=True, verbose_name='Counter'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_tag',
            field=models.TextField(default='#trending #latest', null=True, verbose_name='News tag'),
        ),
    ]
