# Generated by Django 4.1 on 2023-12-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0005_alter_newspost_is_active_alter_newspost_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.CharField(default=None, max_length=11, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='order',
            field=models.CharField(default=None, max_length=11, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='order',
            field=models.CharField(default=None, max_length=11, null=True, unique=True, verbose_name='Order'),
        ),
    ]
