# Generated by Django 4.1 on 2023-12-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0006_category_order_newspost_order_sub_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='BreakingNews',
            field=models.BooleanField(default=False, verbose_name='Breaking News'),
        ),
        migrations.AddField(
            model_name='videonews',
            name='order',
            field=models.CharField(default=None, max_length=11, null=True, unique=True, verbose_name='Order'),
        ),
    ]
