# Generated by Django 4.1 on 2023-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0007_newspost_breakingnews_videonews_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=None, max_length=11, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='order',
            field=models.IntegerField(default=None, max_length=11, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='order',
            field=models.IntegerField(default=None, max_length=11, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='order',
            field=models.IntegerField(default=None, max_length=11, null=True, unique=True, verbose_name='Order'),
        ),
    ]
