# Generated by Django 4.1 on 2023-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0009_videonews_breakingnews_videonews_head_lines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=None, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='BreakingNews',
            field=models.BooleanField(default=False, null=True, verbose_name='Breaking News'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='Head_Lines',
            field=models.BooleanField(default=False, null=True, verbose_name='Head Lines'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='articles',
            field=models.BooleanField(default=False, null=True, verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='is_active',
            field=models.BooleanField(default=False, null=True, verbose_name='Latest News'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='order',
            field=models.IntegerField(default=None, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='trending',
            field=models.BooleanField(default=False, null=True, verbose_name='Trending'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='order',
            field=models.IntegerField(default=None, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='BreakingNews',
            field=models.BooleanField(default=False, null=True, verbose_name='Breaking News'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='Head_Lines',
            field=models.BooleanField(default=False, null=True, verbose_name='Head Lines'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='articles',
            field=models.BooleanField(default=False, null=True, verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='order',
            field=models.IntegerField(default=None, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='trending',
            field=models.BooleanField(default=False, null=True, verbose_name='Trending'),
        ),
    ]
