# Generated by Django 4.1 on 2024-01-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0010_alter_category_order_alter_newspost_breakingnews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='order',
            field=models.IntegerField(default=None, null=True, verbose_name='Order'),
        ),
    ]
