# Generated by Django 4.1 on 2024-01-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0011_alter_newspost_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='order',
            field=models.IntegerField(default=0, null=True, verbose_name='Order'),
        ),
    ]
