# Generated by Django 4.1 on 2024-01-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0012_alter_newspost_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='Event',
            field=models.BooleanField(default=False, null=True, verbose_name='Upcoming Event'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='Event_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Upcoming Event Date'),
        ),
    ]
