# Generated by Django 4.1 on 2024-01-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0014_newspost_eventend_date_newspost_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_title',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='News Head Line'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='video_title',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='Title (Lenth 60 Char)'),
        ),
    ]
