# Generated by Django 4.1 on 2024-03-04 17:53

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0016_videonews_counter_videonews_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videonews',
            name='order',
            field=models.IntegerField(default=10, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='video_thumbnail',
            field=image_cropping.fields.ImageCropField(blank=True, default='thumbnail/na.jpg', max_length=255, null=True, upload_to='thumbnail/', verbose_name='Thumbnail (1280X720px)'),
        ),
    ]
