# Generated by Django 4.1 on 2024-03-22 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0018_newspost_schedule_date_videonews_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='schedule_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Schedule Date'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='schedule_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Schedule Date'),
        ),
    ]
