# Generated by Django 4.1 on 2024-03-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0019_alter_newspost_schedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='subcat_tag',
            field=models.TextField(default='#trending #latest', null=True, verbose_name='Cat tag'),
        ),
    ]
