# Generated by Django 4.1 on 2024-05-25 07:44

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_management', '0022_videonews_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=200, null=True, populate_from='post_title', unique=True),
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200, null=True, verbose_name='News Head Line')),
                ('des', models.CharField(default=None, max_length=300, null=True, verbose_name='Short Discretion')),
                ('sliderimage', image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='blog/', verbose_name='Slider Image (1400X520px)')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=200, null=True, populate_from='slidercat', unique=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=5, null=True, verbose_name='Order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slidercat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.sub_category', verbose_name='Select Cetegory')),
            ],
        ),
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(default=None, max_length=150, null=True, verbose_name='News Head Line')),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(default='No News', null=True, verbose_name='Long Discretion')),
                ('pageimage', image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='cms/', verbose_name='Page Image (1280X220px)')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=200, null=True, populate_from='pagename', unique=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewcounter', models.IntegerField(default=0, null=True, verbose_name='Views')),
                ('post_status', models.IntegerField(default=100, null=True, verbose_name='Counter')),
                ('order', models.IntegerField(default=5, null=True, verbose_name='Order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
