# Generated by Django 5.1.4 on 2025-02-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0023_alter_newspost_slug_slider_cms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videonews',
            name='viewcounter',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='Views'),
        ),
    ]
