# Generated by Django 5.1.4 on 2025-04-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0025_newspost_journalist_alter_newspost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='subcat_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'pending'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status'),
        ),
    ]
