# Generated by Django 5.1.4 on 2025-04-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0026_alter_sub_category_subcat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='subcat_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='active', max_length=8, verbose_name='Status'),
        ),
    ]
