# Generated by Django 5.1.7 on 2025-04-09 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0004_alter_journalist_biography'),
        ('post_management', '0030_alter_newspost_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videonews',
            name='journalist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='journalist.journalist'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='is_active',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='active', max_length=8, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='order',
            field=models.IntegerField(default=5, null=True, verbose_name='Order'),
        ),
    ]
