# Generated by Django 5.1.4 on 2025-06-14 14:03

import autoslug.fields
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0031_videonews_journalist_alter_videonews_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_image',
            field=image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='media/%Y/%m/%d', verbose_name='News Image (1280X720px)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post_management.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='videonews',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post_management.tag', verbose_name='Tags'),
        ),
    ]
