# Generated by Django 4.2.7 on 2025-06-18 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0032_tag_alter_newspost_post_image_newspost_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Status'),
        ),
    ]
