# Generated by Django 4.2.7 on 2025-08-02 12:50

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_management', '0033_tag_create_date_tag_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='meta_title',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='Meta Title(35 to 65 chr standard)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, max_length=200, populate_from='meta_title', unique=True),
        ),
    ]
