# Generated by Django 5.2.6 on 2026-01-06 11:57

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0034_newspost_meta_title_tag_author_alter_newspost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_image',
            field=image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='newsimage/%Y/%m/%d', verbose_name='News Image (1280X720px)'),
        ),
    ]
