# Generated by Django 5.2.3 on 2026-03-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0035_appuser_alter_newspost_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
