# Generated by Django 5.2.4 on 2026-04-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0037_newsredirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('is_bot', models.BooleanField(default=False)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
