# Generated by Django 5.2.4 on 2026-04-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0038_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
