# Generated by Django 5.1.4 on 2025-04-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0002_qualification_alter_journalist_higher_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalist',
            name='message',
        ),
        migrations.AddField(
            model_name='journalist',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='biography (max 120 characters 135)'),
        ),
    ]
