# Generated by Django 5.1.4 on 2025-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0003_remove_journalist_message_journalist_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='biography (max 120 characters)'),
        ),
    ]
