# Generated by Django 5.1.4 on 2025-05-08 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0004_alter_journalist_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='gallery_post_limit',
            field=models.PositiveIntegerField(default=8, verbose_name='Gallery Post Limit'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalist',
            name='parent_organisations',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='journalist',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('artist', 'Artist'), ('journalist', 'Journalist'), ('organisation', 'Organisation')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='journalist')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=8)),
                ('post_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='journalist.journalist')),
            ],
        ),
    ]
