# Generated by Django 5.1.4 on 2025-05-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0005_journalist_gallery_post_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
    ]
