# Generated by Django 5.1.4 on 2025-05-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0006_journalist_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved')], default='inactive', max_length=8),
        ),
    ]
