# Generated by Django 4.2.7 on 2025-06-18 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0005_journalist_organisation_name_and_more'),
        ('journalist', '0007_alter_journalist_status'),
    ]

    operations = [
    ]
