# Generated by Django 5.1.4 on 2025-07-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0008_merge_20250618_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
