# Generated by Django 5.1.4 on 2025-07-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0009_gallery_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
