# Generated by Django 4.1 on 2024-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='subcat_status',
            field=models.CharField(choices=[('stil', 'Image'), ('video', 'Video')], default='active', max_length=8, verbose_name='Status'),
        ),
    ]
