# Generated by Django 4.1 on 2024-01-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_management', '0002_ad_subcat_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='subcat_status',
            new_name='ad_type',
        ),
    ]
