# Generated by Django 4.2.7 on 2025-04-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_management', '0003_rename_subcat_status_ad_ad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('stil', 'Image'), ('video', 'Video')], default='active', max_length=8, verbose_name='Ad Type'),
        ),
    ]
